# Navigation Links

main:
  - name: Bio
    url: /
    weight: 10
  - name: Work
    url: /#projects
    weight: 11
  - name: Skills
    url: /#skills
    weight: 12
  - name: Experience
    url: /#experience
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Publications
    url: /#papers
    weight: 40
  - name: Contact
    url: /#contact
    weight: 50
